import streamlit as st
from st_supabase_connection import SupabaseConnection
import app.initialize as session_init
from app.common import load_scan_cache, save_scan_cache
import datetime
import uuid

st.set_page_config(page_title="Flooding Coordination - Bounty Board", layout="wide")
session_init.init_session_state()

st.title("Disaster Bounty Board")
st.markdown("Connect with real-time needs and system-generated alerts.")

# Initialize Supabase Connection
try:
    conn = st.connection("supabase", type=SupabaseConnection)
except Exception as e:
    st.error(f"Failed to connect to Supabase: {e}")
    conn = None

# Helper Functions

def load_bounties():
    """Fetch help requests from Supabase."""
    if not conn:
        return []
    try:
        user_id = st.session_state.get("user_id")
        if user_id:
            response = conn.table("help_requests").select("*").neq("poster_id", user_id).order("created_at", desc=True).execute()
            # Filter out bounties where user is already a volunteer or applicant
            filtered_data = [
                b for b in response.data 
                if st.session_state.get("user_id") not in (b.get('current_volunteers') or []) 
                and st.session_state.get("user_id") not in (b.get('applicants') or [])
            ]
            return filtered_data
        else:
            response = conn.table("help_requests").select("*").order("created_at", desc=True).execute()
        return response.data
    except Exception as e:
        st.error(f"Error fetching bounties: {e}")
        return []

def post_bounty(content, lat, lon, disaster_type, urgency):
    """Post a new help request to Supabase."""
    user_id = st.session_state.get("user_id")
    if not user_id:
        st.error("You must be logged in to post.")
        return False
    
    if not conn:
        st.error("Database connection unavailable.")
        return False

    try:
        conn.table("help_requests").insert({
            "poster_id": user_id,
            "content": content,
            "lat": lat,
            "long": lon,
            "disaster_type": disaster_type,
            "urgency": urgency,
        }).execute()
        return True
    except Exception as e:
        st.error(f"Failed to post bounty: {e}")
        return False


def apply_for_bounty(bounty_id, current_applicants):
    """Add current user to applicants list."""
    user_id = st.session_state.get("user_id")
    if not user_id:
        st.warning("Please log in to apply.")
        return False
    
    if not conn:
        return False
    
    # Handle None case
    if current_applicants is None:
        current_applicants = []
        
    if user_id in current_applicants:
        st.info("You already applied!")
        return False

    updated_applicants = current_applicants + [user_id]
    
    try:
        conn.table("help_requests").update({"applicants": updated_applicants}).eq("id", bounty_id).execute()
        return True
    except Exception as e:
        st.error(f"Failed to apply: {e}")
        return False

@st.dialog("Bounty Details")
def show_bounty_details(b):
    user_id = st.session_state.get("user_id")
    
    st.subheader(f"{b['disaster_type']} - Urgency: {b['urgency']}/10")
    st.write(b['content'])
    st.markdown(f"**Location:** {b['lat']}, {b['long']}")
    st.caption(f"Posted: {b['created_at']}")
    
    volunteers = b.get('current_volunteers', []) or []
    if volunteers:
        st.write(f"**Active Volunteers:** {len(volunteers)}")
    
    st.divider()
    
    col1, col2 = st.columns(2)

    is_creator = user_id == b['poster_id']
    
    with col1:
        if not is_creator and st.button("📩 DM Creator", key=f"dm_{b['id']}"):
            st.switch_page("pages/5_Groups.py", query_params={"dm_id": b['poster_id']})
            
    with col2:
        applicants = b.get('applicants', []) or []
        is_applicant = user_id in applicants
        is_volunteer = user_id in volunteers
        
        if is_creator:
            st.info("You posted this bounty. Go to Profile to manage.")
        elif is_volunteer:
            st.success("You are volunteering!")
        elif is_applicant:
            st.info("Application Pending")
        else:
            if user_id:
                if st.button("Apply to Help", key=f"apply_{b['id']}", use_container_width=True):
                    if apply_for_bounty(b['id'], applicants):
                        st.success("Applied successfully!")
                        st.rerun()
            else:
                if st.button("Log in to Apply", key=f"login_apply_{b['id']}", use_container_width=True):
                    st.switch_page("pages/1_Login.py")

# --- UI Sections ---

col_alerts, col_community = st.columns([1, 1])

# 1. System Alerts (from Scanner/Chatbot)
with col_alerts:
    st.subheader("🚨 System & Chatbot Alerts")
    st.caption("Generated by AI monitoring and news scanning.")
    
    # Reload cache to ensure we have simplest source of truth
    if "scan_results" not in st.session_state:
         cached = load_scan_cache()
         st.session_state.scan_results = cached.get("scan_results", [])
    
    alerts = st.session_state.scan_results
    
    if not alerts:
        st.info("No active system alerts detected.")
    else:
        for alert in alerts[:20]: # Limit to top 20
            with st.expander(f"{alert.get('disaster_type', 'Alert')} near {alert.get('location', 'Unknown')}", expanded=True):
                st.write(alert.get('summary', 'No details provided.'))
                st.write(f"**Severity:** {alert.get('severity', 0)}/10")
                if alert.get('source'):
                    st.caption(f"Source: {alert.get('source')}")

# 2. Community Bounties (Supabase)
with col_community:
    row_header = st.columns([3, 1])
    row_header[0].subheader("🆘 Community Bounties")
    
    # "Post Request" Button
    with row_header[1]:
        if st.button("Post", icon=":material/add:"):
            # Use a dialog for simpler interaction
            @st.dialog("Post Help Request")
            def item_dialog():
                with st.form("new_bounty_form"):
                    b_content = st.text_area("What do you need help with?")
                    c1, c2 = st.columns(2)
                    b_lat = c1.number_input("Latitude", value=0.0, format="%.4f")
                    b_lon = c2.number_input("Longitude", value=0.0, format="%.4f")
                    b_type = st.selectbox("Type", ["Flood", "Fire", "Medical", "Supplies", "Rescue", "Other"])
                    b_urgency = st.slider("Urgency (1-10)", 1, 10, 5)
                    
                    if st.form_submit_button("Submit Request"):
                        if post_bounty(b_content, b_lat, b_lon, b_type, b_urgency):
                            st.success("Posted!")
                            st.rerun()
            
            item_dialog()

    st.caption("Real-time requests from users.")
    
    bounties = load_bounties()
    
    if not bounties:
        st.info("No active help requests.")
    else:
        for b in bounties:
            b_id = b['id']
            volunteers = b.get('current_volunteers', []) or []
            applicants = b.get('applicants', []) or []
            
            card_color = "red" if b['urgency'] > 7 else "orange" if b['urgency'] > 4 else "green"
            
            with st.container(border=True):
                c_main, c_act = st.columns([6, 2])
                with c_main:
                    st.markdown(f"**:{card_color}[{b['disaster_type'].upper()}]** • Urgency: {b['urgency']}/10")
                    st.write(b['content'][:100] + ("..." if len(b['content']) > 100 else ""))
                    st.caption(f"📍 {b['lat']}, {b['long']} • {len(volunteers)} volunteers")
                
                with c_act:
                    if st.button("View", key=f"view_{b_id}"):
                        show_bounty_details(b)

